Note.create(title: 'メモ１', content: '内容１')
Note.create(title: 'メモ２', content: '内容２')
Note.create(title: 'メモ３', content: '内容３')
Note.create(title: 'メモ４', content: '内容４')
Note.create(title: 'メモ５', content: '内容５')